image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - setup
  - build
  - deploy

dependencies:
  stage: setup
  script:
    - npm i

test:
  stage: build
  script:
    - npm run test
  coverage: /All files[^\|]*\|[^\|]*\s+([\d\.]+)/
  artifacts:
    paths:
      - coverage/

pages: 
  stage: deploy
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public/
    expire_in: 30 days
  only:
    - master